#!/bin/bash

search_free_port () {
    for i in {0..9}
        do
            nc -z 127.0.0.1 80$1$i;
            if [ $? -eq 1 ] ; then
                echo 80$1$i
                break
            else
               continue
            fi
        done
}

export puerto_web=$(search_free_port 1)
puerto_xdebug=$(search_free_port 2)
puerto_db=$(search_free_port 3)
export puerto_phpmyadmin=$(search_free_port 4)
puerto_redis=$(search_free_port 5)
puerto_mailhog1=$(search_free_port 6)
export puerto_mailhog2=$(search_free_port 7)

sed -i -e "s/<puerto_web>/$puerto_web/g" docker-compose.yml
sed -i -e "s/<puerto_xdebug>/$puerto_xdebug/g" docker-compose.yml
sed -i -e "s/<puerto_db>/$puerto_db/g" docker-compose.yml
sed -i -e "s/<puerto_phpmyadmin>/$puerto_phpmyadmin/g" docker-compose.yml
sed -i -e "s/<puerto_redis>/$puerto_redis/g" docker-compose.yml
sed -i -e "s/<puerto_mailhog1>/$puerto_mailhog1/g" docker-compose.yml
sed -i -e "s/<puerto_mailhog2>/$puerto_mailhog2/g" docker-compose.yml