#!/usr/bin/env bash
docker-compose up -d && \
version=$(git describe --tags $(git rev-list --tags --max-count=1))
echo "
===================== 🚀 Done 🚀 ===================

      v.$version
      Access your new links:

      🌎 Web server: http://localhost:$puerto_web
      ⚙️ PHPMyAdmin: http://localhost:$puerto_phpmyadmin
      ✉️ Local emails: http://localhost:$puerto_mailhog2

===================== 🚀 Done 🚀 ==================="
